### ISSUE TITLE
White lane

### ISSUE THREAD

**Issue by filkata1996** [anthonynorth/rscodeio#41]
After installing the theme I got this lane on my screen. It's very annoying. I have uninstalled and install the R studio a couple of times. I Changed multiple themes (dark and light), it just stays ..... :( 
Can someone help ?! 
![Capture](https://user-images.githubusercontent.com/61425789/86458748-6b9fc700-bd2e-11ea-92c0-07ef34987f12.PNG)

**Comment by luciorq** [comment]
Hello @filkata1996 

This a programming margin, historically, it was conceived as a good practice to don't write code longer than this size,
because it difficult the reading of code on older computers and terminals, and also is a bad practice if you need to roll your window to the side to see the full code. Or if you plan to print your code to paper, this is also a good limit.

This is an option of RStudio itself and not from the theme, you can change it on:

* Tools > Global Options > Code > Display > Uncheck Show Margin

![image](https://user-images.githubusercontent.com/22479186/86479712-101c0c00-bd23-11ea-82d2-aebed11a1eea.png)

**Comment by salim-b** [comment]
@anthonynorth I think this one can be safely closed, too.
